### PR TITLE
Bug/issue37

### LINKED ISSUE #37: Title in searchScreen articles with white image background can't be seen

### PR DESCRIPTION
**Pull request by veronica-hinojosa**
Closes #37

### CODE REVIEW

File: app/src/main/java/com/wizeline/mobilenews/ui/dashboard/ArticleItem.kt [hunk 1]
```diff
@@ -11,6 +11,7 @@ import androidx.compose.runtime.Composable
 import androidx.compose.ui.Modifier
 import androidx.compose.ui.draw.blur
 import androidx.compose.ui.graphics.Brush
```
Comment (ponchOlvera) [inline app/src/main/java/com/wizeline/mobilenews/ui/dashboard/ArticleItem.kt:13]: There are some imports in the file that are not used any more. Just delete them with `ctrl` + `option` + `o` and you're good to go.

**Review by ponchOlvera — APPROVED** [review]
